# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_vtm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog0")
        Dialog.resize(1111, 845)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 20, 401, 91))
        self.label.setStyleSheet("font: 22pt \"Nirmala Text Semilight\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 941, 481))
        self.label_2.setStyleSheet("font: 22pt \"Nirmala Text Semilight\";")
        self.label_2.setObjectName("label_2")
        self.in_window_model_LC_but = QtWidgets.QPushButton(Dialog)
        self.in_window_model_LC_but.setGeometry(QtCore.QRect(90, 660, 171, 71))
        self.in_window_model_LC_but.setStyleSheet("font: 22pt \"Nirmala Text Semilight\";\n"
"background-color: rgb(41, 46, 79);\n"
"color: rgb(170, 255, 255);")
        self.in_window_model_LC_but.setObjectName("in_window_model_LC_but")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog0):
        _translate = QtCore.QCoreApplication.translate
        Dialog0.setWindowTitle(_translate("Dialog0", "Dialog"))
        self.label.setText(_translate("Dialog0", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600; font-style:italic; color:#94252c;\">MENU</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog0", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">Hello, this is a mini-application for testing and using neural </span></p><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">network models by Alexandra Myasishcheva. </span></p><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">At the moment, the models are available without restrictions. </span></p><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">New developments will be added.</span></p><p><br/></p><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">Social networks of the author:</span></p><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">@lexy_q (telegram)</span></p><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#4856a2;\">@alexandraqq_20 (tik tok)</span></p></body></html>"))
        self.in_window_model_LC_but.setText(_translate("Dialog0", "model_LC"))
